name: apexspeech
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.2.3
  google_fonts: ^8.1.0
  flutter_secure_storage: ^10.3.0
  dio: ^5.9.2
  dartz: ^0.10.1
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^2.0.1
  fl_chart: ^1.2.0
  flutter_sound: ^9.30.0
  speech_to_text: ^7.4.0
  permission_handler: ^12.0.3
  audioplayers: ^6.7.1
  sqflite: ^2.4.3
  sqflite_common_ffi: ^2.4.1
  sqlite3: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#080810"
  adaptive_icon_foreground: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#080810"
    theme_color: "#D4AF37"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png